version: "3.9"
services:
  spring-management-api:
    image: spring-management-api
    container_name: spring-management-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: db_management
    environment:
      MYSQL_ROOT_PASSWORD: DOKY2018
      MYSQL_DATABASE: db_management
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis_management
    ports:
      - "6379:6379"
    networks:
      - spring-network
    volumes:
      - redis-volume:/data

networks:
  spring-network:

volumes:
  mysql-volume:
  redis-volume:
