# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  cache:
    type: redis
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: DOKY2018
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
    redis:
      host: localhost
      port: 6379
      database: 0
flyway:
  enabled: true
  locations: classpath:/db/migration
  baseline-on-migrate: true
  baseline-version: 0

# ===================================================================
# SECURITY PROPERTIES
# ===================================================================
security:
  jwt:
    key: 08af2447a30c9c090b3595e6b45cead32eb587dcb1892aae31f073dcb31bce95
    access:
      expiration: 1800000
    refresh:
      expiration: 86400000
    user:
      generator: management_system
    hashed:
      secret: d0DMBKNAbVqoX6cT00DEpB/T5atRfONxoJpgM7o+dCM=

# ===================================================================
# LOG PROPERTIES
# ===================================================================
api:
  uri:
    domain:
      auth: "/auth"


# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  level:
    root: INFO
    com.tu.paquete: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} [%thread] %clr(%-5level){yellow,red,green,blue,magenta} %clr(%logger{36}){cyan}:%clr(%L){faint} - %msg%n"
    file: "[%X{data}%thread] [%X{X-B3-TraceId:-}] %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36}:%L - %msg%n"